server:
  port: 80
  session:
    timeout: 3600
  tomcat:
    uri-encoding: utf-8
    max-threads: 300
    min-spare-threads: 30
spring:
  application:
    name: clouddisk
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  http:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      location: D://BaiduYunDownload
    encoding:
      charset: UTF-8
  messages:
    basename: i18n/messages_en_US, i18n/messages_zh_CN
   #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///clouddisk?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 101757
    tomcat:
      validation-query: select 1 from dual
      test-while-idle: false
    hikari:
      maximum-pool-size: 10
    dbcp2:
      validation-query: select 1 from dual

mybatis:
  mapper-locations: mapping/*.xml
  type-aliases-package: cn.clouddisk.entity
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
#debug: true
#logging:
#  level:
#    root: warn
#    org:
#      springFramework:
#        web: debug
storePath: E:/BaiduYunDownload/ #本地资源路径必须以/结尾
shiro:
  user:
    loginUrl: /logIn
    indexUrl: /userHome
    unauthorizedUrl: /unauth
  cookie:
    domain:
    path: /
    httpOnly: true
    maxAge: 30
  session:
    expireTime: 30
    dbSyncPeriod: 1
    validationInterval: 10
