server:
  port: 80
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    multipart:
      enabled: true
      max-file-size: 1048576000
  messages:
    basename: i18n/messages, i18n/messages_zh
   #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///clouddisk?characterencoding=utf8&serverTimezone=UTC
    username: root
    password: 101757

mybatis:
  mapper-locations: mapping/*.xml
  type-aliases-package: cn.clouddisk.entity
  configuration:
    cache-enabled: true
